SumoLogic/sumologic-otel-collector-packaging

- targets/otc_linux_arm64_deb.cmake
- targets/otc_linux_arm64_rpm.cmake
Adds arm64/aarch64 deb & rpm packages for linux.
> feat: add linux/arm64 deb & rpm

- .github/workflows/build_packages.yml
Adds GitHub Actions jobs for the linux arm64 deb & rpm packages.
> feat: add linux/arm64 linux jobs

- msi/SumoLogic.wixext/SumoLogic.wixext/Config.cs
- msi/SumoLogic.wixext/SumoLogic.wixext/ConfigUpdater.cs
- msi/SumoLogic.wixext/SumoLogic.wixext/CustomAction.cs
- msi/SumoLogic.wixext/SumoLogic.wixext/Exceptions.cs
- msi/SumoLogic.wixext/SumoLogicTests/ConfigTests.cs
- msi/SumoLogic.wixext/SumoLogicTests/ConfigUpdaterTests.cs
- msi/wix/components.wxs
- msi/wix/folders.wxs
- msi/wix/package.wxs
For Windows installer.
Code copied from https://github.com/SumoLogic/sumologic-otel-collector/pull/1437.
> feat: add support for remote management, ephemeral and api url

- .github/workflows/_reusable_build_package.yml
The bash condition in #49 wasn't completely right.
> ci: fix MacOS signing condition

- .github/workflows/build_packages.yml
This is the same as we currently do in https://github.com/SumoLogic/sumologic-otel-collector, see for example: https://github.com/SumoLogic/sumologic-otel-collector/releases/tag/v0.96.0-sumo-1.
> ci: add install scripts to release artifacts

- .github/workflows/_reusable_build_package.yml
- .github/workflows/build_packages.yml
- msi/SumoLogic.wixext/SumoLogicTests/TestData/with-extensions-block.yaml
- msi/SumoLogic.wixext/SumoLogicTests/TestData/without-extensions-block.yaml
- msi/wix/assets/common.yaml
- msi/wix/otelcol-sumo.wixproj
I've also synced some other changes from the msi package definition in the collector repo.
> Add fips support to msi package

- .github/workflows/build_packages.yml
Automatically generate release notes in the following format: https://github.com/SumoLogic/sumologic-otel-collector-packaging/releases/tag/v0.96.0-1057.
> ci: generate release notes automatically

- .github/workflows/lint.yml
- install-script/install.ps1
- install-script/install.sh
- install-script/test/check.go
- install-script/test/check_windows.go
- install-script/test/consts_common.go
- install-script/test/install_darwin_test.go
- install-script/test/install_unix_test.go
- install-script/test/install_windows_test.go
The changes are: 
- https://github.com/SumoLogic/sumologic-otel-collector/pull/1522
- https://github.com/SumoLogic/sumologic-otel-collector/pull/1523
- https://github.com/SumoLogic/sumologic-otel-collector/pull/1525
After this is merged, we can also merge https://github.com/SumoLogic/sumologic-otel-collector/pull/1526 and remove both the install script and the packages from the collector repository.
> Port recent changes from the collector repo

- .github/workflows/_reusable_build_package.yml
Make the workflow artifact name for msi packages consistent with other artifacts.
> ci: fix msi workflow artifact name

- .github/workflows/build_packages.yml
Fix an unquoted argument in #71
> ci: fix release tag creation

- .github/workflows/build_packages.yml
One more fix for this. :unamused:
> ci: fix release tag user data

- version.cmake
Manual run on fork for `0.99.0-sumo-0-rc.0`: https://github.com/kkujawa-sumo/sumologic-otel-collector-packaging/actions/runs/8966904945
> feat: add support for rc versions

- .github/workflows/_reusable_build_package.yml
- .github/workflows/build_packages.yml
We've added the microsoft code signing secrets to this repo and hooked them up to the reusable build workflow.
> Add windows binary signing CI stage

- install-script/install.sh
Drop workarounds for collector <0.57.0 and <0.71.0 respectively. Both of these are more than a year old and not supported.
Incidentally, we had a bug in our version string parsing that prevented release candidate versions from being correctly compared, but it was easier to delete the whole thing than fix it.
> chore(install.sh): drop workarounds for old collector versions

- .github/workflows/_reusable_build_package.yml
Reverts SumoLogic/sumologic-otel-collector-packaging#95
Build is failing
> Revert "chore(deps): bump robinraju/release-downloader from 1.10 to 1.11"

- .github/workflows/_reusable_build_package.yml
- Dockerfile
- assets/productbuild/uninstall.sh
- ci/verify_installer.sh
- components/otelcol-sumo.cmake
- packages.cmake
- settings/otc.cmake
Adds the otelcol-config binary to the installed components.
> feat: add otelcol-config binary

- settings/deb/common.cmake
Set the missing package release version on Debian.
> fix: set package release version on Debian

- .gitignore
- install-script/install.sh
The install script wasn't properly supporting the fips packages:
* prepackaging check wasn't checking if the fips package was installed
* install / upgrade instructions didn't support fips package
> fix(install-script): support fips packages

- .github/ISSUE_TEMPLATE/opentelemetry-collector-release.md
Based on https://docs.google.com/document/d/1NnNJWyVc-1NX4RX0_LARKnLEC_et_w8lURh0g4gWNd8/edit?tab=t.0
> New issue template for otel collector releases

- .github/workflows/_reusable_build_package.yml
- .github/workflows/build_packages.yml
- msi/SumoLogic.wixext/SumoLogicTests/SumoLogicTests.csproj
https://github.com/actions/runner-images/issues/12045 2019 is deprecated
> Windows runner shift to 2022

- install-script/install.ps1
- msi/SumoLogic.wixext/SumoLogic.wixext/Config.cs
- msi/SumoLogic.wixext/SumoLogic.wixext/ConfigUpdater.cs
- msi/SumoLogic.wixext/SumoLogic.wixext/CustomAction.cs
- msi/SumoLogic.wixext/SumoLogicTests/ConfigUpdaterTests.cs
- msi/wix/package.wxs
This will allow us to add Timezone in add OT collector workflow
To be merged after https://github.com/SumoLogic/sumologic-otel-collector/pull/1770
> Add --timezone flag to windows install script

- .github/workflows/workflow-promote.yml
https://sumologic.slack.com/archives/C093VHX53GU/p1757518165159889?thread_ts=1757434400.555029&cid=C093VHX53GU
> Fix Promote worklow
