SumoLogic/sumologic-otel-collector-packaging

assets/productbuild/uninstall.sh, ci/verify_installer.sh, components/otelcol-sumo.cmake, settings/otc.cmake, templates/hooks/common/otc-darwin-functions.in
The otelcol-sumo LaunchDaemon writes stdout & stderr to `/var/log/otelcol-sumo/otelcol-sumo.log`. This currently fails after a fresh installation as the package doesn't create the `/var/log/otelcol-sumo directory`. This change adds the directory to the otelcol-sumo component for Darwin packages.
=> fix: add /var/log/otelcol-sumo on darwin

assets/sumologic.yaml
Renames `SUMOLOGIC_INSTALL_TOKEN` to `SUMOLOGIC_INSTALLATION_TOKEN` to match https://github.com/SumoLogic/sumologic-otel-collector/blob/main/examples/sumologic.yaml.
=> fix: Rename SUMOLOGIC_INSTALL_TOKEN to SUMOLOGIC_INSTALLATION_TOKEN

packages.cmake
Remotely triggered builds broke when https://github.com/SumoLogic/sumologic-otel-collector-packaging/pull/2 was merged. The custom target for copying the binary artifact downloaded from GitHub to the artifacts directory is not a dependency of package target (`make package`) so it never runs. This adds the custom target to all build targets and resolved the issue in my tests: https://github.com/SumoLogic/sumologic-otel-collector-packaging/actions/runs/4962831296.
=> fix: add binary target to default build target

.github/workflows/_reusable_build_package.yml, .github/workflows/build_packages.yml, settings/productbuild/otc.cmake
Adds package signing for Mac packages.
The existing Apple certificate used in the sumologic-otel-collector is the wrong type for signing packages. Here's what still needs to happen before this PR will function:
1. A `Developer ID Installer` certificate needs to be generated
1. The certificate needs to be converted to base12
1. Update the GitHub Secret `APPLE_DEVELOPER_CERTIFICATE_P12_BASE64` with the base12 value
1. Update the GitHub Secret `APPLE_DEVELOPER_CERTIFICATE_PASSWORD` with the certificate password
1. Update the GitHub Variable `APPLE_DEVELOPER_CERTIFICATE_IDENTITY` with the identity of the new certificate (e.g. `Developer ID Installer: Sumo Logic, Inc. (XXXXXXXXXX)`)
To test the CMake changes I generated a certificate using my personal Apple Developer Account and then ran the …
=> feat: sign mac packages

assets/productbuild/uninstall.sh
Mac pkg uninstallation currently leaves a collector running (now without a plist to manage it). This PR adds support for stopping the collector service before uninstalling the package.
=> Unload the collector service before uninstalling package

.github/workflows/_reusable_build_package.yml
The `OTC_ARTIFACTS_SOURCE` environment variable is used in CMake to skip the downloading of artifacts from a GitHub Release in situations where those artifacts (e.g. otelcol-sumo binary) already exist. The environment variable is currently only set in the Docker `entrypoint.sh` file which is exclusively used for Linux packages. This change adds the setting of `OTC_ARTIFACTS_SOURCE` for non-Docker builds (e.g. macOS).
=> Set OTC_ARTIFACTS_SOURCE in non-Docker builds

assets/conf.d/common.yaml, ci/verify_installer.sh, components/otelcol-sumo.cmake
Adds an empty `token.env` file on Linux and `common.yaml` with a basic structure on Darwin & Linux. This will allow ownership & permissions for those files to be controlled by packaging rather than the install script.
=> feat: add token.env and common.yaml

msi/SumoLogic.wixext/SumoLogic.wixext/SumoLogic.wixext.csproj, msi/wix/folders.wxs, msi/wix/otelcol-sumo.wixproj, msi/wix/ui/otelcol-sumo.wxs, msi/wix/variables.wxi
Bumps the WiX toolset version from 4.0.0-preview.1 to 4.0.1.
In order to get this to build I had to update some of our custom WixUI code:
* The UI element's `Id` attribute now requires the platform that the UI is built for.
* The `Print` control for the EULA had no action and did nothing. I've added the proper line to fix it.
I found a few other recommendations and one bug:
* The `Next` control for the `CustomizeDlg` page was going to `VerifyReadyDlg` instead of `ConfigurationDlg`. This prevented the dialog that asks for the `InstallToken` and `Tags` from appearing unless the  `Back` control was clicked on the `VerifyReadyDlg` page.
* Removed the `PlatformProgramFilesFolder` variable and logic to determine which Program Files directory to use depending on the platform. This is now handled …
=> chore: bump wix toolset version to 4.0.1

.github/workflows/_reusable_build_package.yml
The file name used to find the remote artifact for Windows binaries is missing the .exe extension.
=> fix: add missing .exe to artifact name

templates/hooks/common/otc-darwin-functions.in
Sets the owner of `/etc/otelcol-sumo` to the service user (`_otelcol-sumo`) on macOS. The Linux equivalent change is made in #28.
=> chore: set /etc/otelcol-sumo owner to _otelcol-sumo on mac

assets/deb/conffiles
Adds `common.yaml` to the debian `conffiles` file to specify it as a configuration file. This prevents packages from overwriting local changes to `common.yaml`.
=> chore: add common.yaml to deb conffiles

assets/conf.d/common.yaml, assets/deb/conffiles, components/otelcol-sumo.cmake, settings/rpm/common.cmake, settings/rpm/otc.cmake, templates/hooks/common.cmake, templates/hooks/common/otc-linux-functions.in, templates/hooks/rpm/after-install.in
Files with `440` permissions can be too restrictive in cases where the install script needs to be able to add/modify/remove values for tags, api_base_url, etc.
Also adds `collector_fields` with no value to `common.yaml` and sets `common.yaml` as a config file within RPMs.
=> File ownership & permissions changes

.github/workflows/_reusable_build_package.yml
Fixes CI builds after they recently broke. Forces the workflow name to search for artifacts from and will only use them if the remote workflow succeeded.
=> fix: set workflow filename

settings/otc.cmake, templates/hooks/common/darwin-functions.in, templates/hooks/productbuild/preflight.in
This basically does for Darwin the same thing the install script does for Linux. Tested it locally and it worked.
=> Set the right ACLs on system log files in the darwin package

.github/workflows/build_packages.yml
Use workflow inputs instead of Github event attributes. This way, we don't get into any weird edge cases involving defaults. As is, the default for `release` is `false`, but if we trigger the workflow remotely, this attribute is empty and we create the release even when we shouldn't.
=> ci: fix build packages workflow

.github/workflows/_reusable_build_package.yml
PR checks on dependabot PRs are failing due to not having access to the MacOS signing certificate. This change simply disables signing if the secret isn't available.
=> ci: only sign Mac packages if required secrets are present

.github/workflows/_reusable_build_package.yml
When running from a triggered dev build in the collector repo, the source and destination filename can be the same. Ensure this doesn't cause an error.
=> ci: resolve msi filename conflicts

.github/workflows/_reusable_build_package.yml
#58 has a bug where we don't set the artifact name correctly and download all of them as a result. Release builds are fine, as they get artifacts from the release, but dev builds have since been failing.
=> ci: fix msi workflow artifact name

.github/workflows/_reusable_build_package.yml
The action we're using hasn't been updated to Node 20, and GHA will stop supporting it soon.
=> ci: import macos code signing certs using custom script

.github/workflows/build_packages.yml
Add a message to the release tag containing the Otel application version used by the released packages. This is to make it easier for us to relate app versions to package versions.
=> ci: add message containing app version to release tags

.github/workflows/build_packages.yml
Finally fix annotated release tags for releases. Turns out you need to create a tag object, and then a tag ref pointing to that object. This now works correctly, see: https://github.com/SumoLogic/sumologic-otel-collector-packaging/releases/tag/v0.97.0-1187.
=> ci: create a git ref for the annotated release tag

.github/workflows/test-install-script.yml
The setup-go github action is currently broken for darwin. The setup-go-faster github action is presumably not broken, and is also faster.
=> Use the setup-go-faster github action

.github/workflows/test-install-script.yml
It seems setup-go-faster requires the go-version input. The previous PR did not fail, even though setup-go-faster was not able to run. (Based on another PR failing, see https://github.com/SumoLogic/sumologic-otel-collector-packaging/actions/runs/8885086917/job/24395622976)
It turns out that the test was not run, because the tests are only run if the install script changes.
I've modified this, so that the test is also run when the .github directory changes.
=> Fix setup-go-faster

.gitignore, install-script/install.sh, install-script/test/check.go, install-script/test/command_unix.go, install-script/test/config.go, install-script/test/install_unix_test.go
This commit adds a new flag to the install script, responsible for setting the OpAmp API URL.
Previously, the OpAmp API URL was computed from the API URL. However, this did not work correctly in all scenarios.
This change is related to a pending change in the agent and may need to be held back until the agent change is committed.
See https://github.com/SumoLogic/sumologic-otel-collector/pull/1519
=> Add --opamp-api-url flag to unix install script

.github/sync.yml, .github/workflows/sync.yml, assets/sumologic-windows.yaml, assets/sumologic.yaml
Enables synchronization of sumologic.yaml & sumologic-windows.yaml from this repository to the https://github.com/sumologic/sumologic-otel-collector repository. This will enable us to make config changes in one repository while ensuring that the files in both repository stay in sync.
=> ci: sync sumologic.yaml & sumologic-windows.yaml to otelcol repo

install-script/install.ps1, install-script/install.sh, install-script/test/check.go, install-script/test/command_unix.go, install-script/test/command_windows.go, install-script/test/common_unix.go, install-script/test/common_windows.go, install-script/test/consts_common.go, install-script/test/install_unix_test.go, install-script/test/install_windows_test.go
This reverts commit 74ff6d891871e3a803a249c466ad6a7887382aa7, reversing changes made to 413816625d3b77aa12d5cf9ab98ac75f2c893fd5.
Users are getting confused by the errors shown by installation telemetry in the Windows installation script. This commit reverts the work done to add installation telemetry until we can determine how to make this less confusing. Tested on my local Windows VM by ensuring that the S3M flow still works to add a collector.
=> Revert "Merge pull request #64 from SumoLogic/222461-installation-logs"

.github/workflows/_reusable_build_package.yml, .github/workflows/build_packages.yml, .github/workflows/test-install-script.yml, install-script/test/consts_common.go, install-script/test/install_windows_test.go
This PR will help in making request to github after authentication. Related [issue](https://github.com/SumoLogic/sumologic-otel-collector-packaging/issues/79)
=> Add GitHub authentication

install-script/install.sh
There's an issue with the script when we hit the github rate limit. When this happens we download an RC if its the most recent release. One could reproduce this by running the old curl command that this PR replaces.
=> fix(install): Fix script to always install the latest stable version

assets/otelcol-sumo.sh
This commit adds a script that calls `exec otelcol-sumo` with either the --config or --remote-config flags, based on the presence of /etc/otelcol-sumo/sumologic-remote.yaml. Using exec replaces the shell with otelcol-sumo, so it doesn't appear in the process list as the shell script. This allows us to correctly invoke otelcol-sumo from systemd and launchd.
=> Add wrapper script for otelcol-sumo

.github/workflows/_reusable_build_package.yml, .github/workflows/build_packages.yml, .github/workflows/test-install-script.yml, install-script/test/Makefile
We currently pull artifacts from GitHub Releases by default when building in this repository. Successful runs for the `Dev builds` workflow in the https://github.com/sumologic/sumologic-otel-collector repository will trigger package builds here that will use artifacts from Github Actions.
The default poses a problem where the only way to test some changes in this repository is to wait for a new release in the https://github.com/sumologic/sumologic-otel-collector repository.
This change updates the CI code to pull artifacts from GitHub CI by default which will make packaging changes more safe and allow us to iterate more quickly.
Once this is merged I will have to update the CI code in https://github.com/sumologic/sumologic-otel-collector to set `use_release_artifacts: true` when …
=> ci: build from GitHub Action artifacts by default

.github/workflows/build_packages.yml, packages.cmake, settings.cmake, settings/deb/otc.cmake, settings/deb/otc_fips.cmake, settings/otc.cmake, settings/rpm/otc.cmake, settings/rpm/otc_fips.cmake, targets/otc_fips_linux_amd64_deb.cmake, targets/otc_fips_linux_amd64_rpm.cmake, targets/otc_fips_linux_arm64_deb.cmake, targets/otc_fips_linux_arm64_rpm.cmake
Adds packages (named `otelcol-sumo-fips`) containing fips binaries for otelcol-sumo & otelcol-config. I've configured the packages to ensure `otelcol-sumo` and `otelcol-sumo-fips` cannot be installed side-by-side on the same system. Users who want to switch between the binaries will need to first uninstall the currently installed package.
Signed-off-by: Justin Kolberg <amd.prophet@gmail.com>
=> feat: add fips targets for linux/amd64 & linux/arm64

install-script/install.sh
* (Linux-only) Prevents installing over an existing package installation. Shows a message with instructions on how to upgrade.
* (Linux-only) Adds the package name to the upgrade commands.
=> chore(install-script): show upgrade instructions

assets/sumologic.yaml
The opamp config is generated by otelcol-config and placed in a separate sumologic-remote.yaml file. Opamp configuration should not be in the non-remote config.
=> Remove opamp config from sumologic.yaml

assets/deb/conffiles, ci/verify_installer.sh, components/otelcol-sumo.cmake, settings/rpm/otc.cmake, templates/hooks/common/otc-linux-functions.in
* Removes the unused `common.yaml` file on Linux & Darwin
* Check for `capset` command and display warning if it is not found
Signed-off-by: Justin Kolberg <amd.prophet@gmail.com>
=> Remove common.yaml on *nix, check for capset

install-script/install.ps1, install-script/install.sh, install-script/test/install_darwin_test.go
Fixes an unbounded variable error in `install.sh` and checks `$env:SKIP_ARCH_DETECTION` for `$null` in `install.ps1`
=> fix(install-script): fix unbounded variable & null check

distributions/fedora.cmake, targets/otc_fips_linux_amd64_rpm.cmake, targets/otc_fips_linux_arm64_rpm.cmake, targets/otc_linux_amd64_rpm.cmake, targets/otc_linux_arm64_rpm.cmake
Adds Fedora 41 to the list of Linux distributions we upload packages for. Removes Fedora 39 as Fedora only supports the last two releases.
Closes #132
=> feat: add fedora 41, rm fedora 39

msi/wix/components.wxs
Sets the LoadOrderGroup to require network connectivity before the service can start.
=> fix(wix): set LoadOrderGroup

.github/workflows/build_packages.yml, .github/workflows/lint.yml, .github/workflows/releases.yml
The following warnings are being produced by every CI run:
```
ubuntu-latest pipelines will use ubuntu-24.04 soon. For more details, see https://github.com/actions/runner-images/issues/10636
```
We can get around this by setting the runner version explicitly.
=> chore(ci): use ubuntu-24.04 runner

.github/workflows/_reusable_build_package.yml, .github/workflows/build_packages.yml, .github/workflows/releases.yml
Adds version artifacts to the build workflow so that the release workflow can use version information to generate the release.
Draft release built using the fixed releases workflow: https://github.com/SumoLogic/sumologic-otel-collector-packaging/releases/tag/untagged-964d375434d9c7be36ff
=> Use version artifacts with release workflow

install-script/install.sh
When running the installer on Mac and Linux it was found that there is a warning about OTRM still being in beta. This PR removes the warning since OTRM is now GA.
=> fix(install-script): Remove OTRM beta warning

install-script/install.sh
This commit fixes an issue in the install script where the fips package can be installed and upgraded, but not removed, as the specified package name is incorrect in the uninstall function.
Fixes #145
=> fix(install-script): fix fips uninstaller

.github/workflows/build_packages.yml, .github/workflows/releases.yml
The Ubuntu 20.04 runners will stop functioning this week. These changes pin our runners to Ubuntu 24.04.
=> chore: update ubuntu runners to 24.04

distributions/fedora.cmake, targets/otc_fips_linux_amd64_rpm.cmake, targets/otc_fips_linux_arm64_rpm.cmake, targets/otc_linux_amd64_rpm.cmake, targets/otc_linux_arm64_rpm.cmake
Adds Fedora 42 to the list of Linux distributions we upload packages for. Removes Fedora 40 as Fedora only supports the last two releases.
=> feat: add fedora 42, rm fedora 40

docs/release-candidate.md, docs/release.md
Adds documentation for the package & artifact promotion from `ci-builds` to `release-candidates` and from `release-candidates` to `stable`.
=> docs: add promotion docs

install-script/install.sh
current set timezone logic for linux only executes for locally managed collector, making it common for both local and remote 
**Mac Remotely managed**
**Mac locally managed**
**Linux remote**
**Linux Local**
=> bug: add timezone for linux remotely managed collector

.github/workflows/workflow-promote.yml
Adds the GOPATH bin directory to PATH so that the packagecloud binary can be found.
=> ci: add GOPATH bin to PATH

.github/workflows/workflow-promote.yml
The promote workflows currently use the append operator `>>` instead of the redirect operator `>` to write the latest version to the `latest_version` file. This creates an issue for the destination bucket as there is already content in the `latest_version` file from when we update the source bucket. This PR fixes that behaviour.
=> fix(ci): overwrite previous latest_version content

install-script/install.sh
Recording write timezone for linux 
**Remote New Machine**
[ec2-user@ip-172-31-41-12 ~]$ cat ./install.sh | SUMOLOGIC_INSTALLATION_TOKEN="U1VNT0w1aWs2bzJoVHI0ZXdkNjVoQ3FKVDhVc1FWTnBodHRwczovL3N0YWctZXZlbnRzLnN1bW9sb2dpYy5uZXQ=" sudo -E bash -s -- --remotely-managed --tag "host.group=default" --tag "deployment.environment=default" --api https://stag-open-events.sumologic.net/ --opamp-api wss://stag-opamp-events.sumologic.net/v1/opamp --timezone Asia/Kolkata -v 0.130.1-2196
DOWNLOAD_URI = https://download-otel.sumologic.com
Detected OS type:       linux
Detected architecture:  amd64
Version specified: 0.130.1-2196
Detected operating system as amzn/2023.
Checking for curl...
Detected curl...
Downloading repository file: https://packages.sumologic.com/install/repositories/sumologic/stable/conf …
=> bug:adding timezone support for linux
